plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java, plugin/src/test/groovy/org/openrewrite/gradle/RewritePluginTest.groovy
In order to be more discreet with usage, unlink rewriteWarn from check by default. rewriteWarn can be wired into dependsOn check through build.gradle config if desired.
May warrant docs update. May need to cross-reference with Maven plugin functionality.
=> Remove rewriteWarn task dependsOn link to check task

plugin/src/main/java/org/openrewrite/gradle/RewriteDryRunTask.java, plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java, plugin/src/main/java/org/openrewrite/gradle/RewriteRunTask.java, plugin/src/test/groovy/org/openrewrite/gradle/RewritePluginTest.groovy
- Follow-up to https://github.com/openrewrite/rewrite-gradle-plugin/pull/25
- closes #20
- See also: openrewrite/rewrite-maven-plugin#110
- Warrants a major version bump.
=> rename tasks rewriteWarn to rewriteDryRun and rewriteFix to rewriteRun

plugin/build.gradle.kts, plugin/src/main/java/org/openrewrite/gradle/AbstractRewriteTask.java, plugin/src/test/groovy/org/openrewrite/gradle/RewritePluginTest.groovy
Consumes upstream changes in rewrite itself, resolves https://github.com/openrewrite/rewrite-gradle-plugin/issues/33
=> upstream rewrite core fixes resolve downstream gradle plugin classpath and deserialization issues

plugin/src/main/java/org/openrewrite/gradle/AbstractRewriteTask.java, plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java
conceptually part of https://github.com/openrewrite/rewrite-gradle-plugin/issues/45 and builds on the work done in https://github.com/openrewrite/rewrite-gradle-plugin/commit/b2e408eaf268600c16f38a46592457cb77933321
`setFailOnInvalidActiveRecipes(true)` to throw an exception on activeRecipeValidationErrors. By default, it's `false` to maintain status quo. In future major versions if we decide on it, we can make it more restrictive to be `true` by default.
By default:
```
Using active recipe(s) [org.openrewrite.java.testing.junit5.JUnit5BestPractices]
Using active styles(s) []
Validating active recipes...
Recipe validation error in org.openrewrite.java.testing.junit5.JUnit4to5Migration.recipeList[8] (in jar:file:/Users/aegershman/.gradle/caches/modules-2/files-2.1/org.openrewrite.recipe/rew …
```
=> setFailOnInvalidActiveRecipes to configure handling activeRecipe validation errors throwing exceptions

plugin/src/main/java/org/openrewrite/gradle/AbstractRewriteTask.java, plugin/src/main/java/org/openrewrite/gradle/RewriteDryRunTask.java, plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java
Addresses https://github.com/openrewrite/rewrite-gradle-plugin/issues/42 and https://github.com/openrewrite/rewrite-maven-plugin/issues/139
Configurable flag for determining whether to fail on dry run results. Currently, default is not to fail. This allows a user to configure having dryRun outputting changes result in an exception and thus non-zero exit code.
```kt
rewrite {
failOnDryRunResults = true
}
```
Example in the case of dryRun producing a result set:
```log
Running recipe(s)...
These recipes would make results to src/main/java/io/slugstack/oss/unspecifiedgradleproject/UnspecifiedGradleProjectApplication.java:
org.openrewrite.java.format.AutoFormat
Report available:
/Users/aegershman/projects/slugstack/slugstack-unspecified-gradle-project/build/reports/rewrite/main.patch
Run 'mvn …
```
=> Configurable failOnDryRunResults

plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
fixes https://github.com/openrewrite/rewrite-gradle-plugin/issues/32
In order to enable users to execute recipes which solves _most_ problems (but technically leaves the source code in a non-compilable state), remove the link between `rewriteRun` and `compile`. The link appears to exist for validation purposes, but is not strictly necessary.
This is valuable in situations where a recipe gets 90% of work done, but still requires a smidgeon of manual intervention.
=> unlink rewriteRun and compile tasks to allow partially-complete transformations to execute

plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
supercedes https://github.com/openrewrite/rewrite-gradle-plugin/pull/55 - this ensures that if both `compile` and `rewriteRun` (or rewriteDryRun) tasks are scheduled for execution, that `compile` should be executed first.
=> Order compilation before rewriteRun and-or rewriteDryRun

plugin/src/main/java/org/openrewrite/gradle/AbstractRewriteTask.java, plugin/src/main/java/org/openrewrite/gradle/RewriteDiscoverTask.java, plugin/src/main/java/org/openrewrite/gradle/RewriteDryRunTask.java, plugin/src/main/java/org/openrewrite/gradle/RewriteJavaMetadata.java, plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java, plugin/src/main/java/org/openrewrite/gradle/RewriteReflectiveFacade.java, plugin/src/main/java/org/openrewrite/gradle/RewriteRunTask.java
=> Adding Java provenance info to gradle-based builds

gradle/wrapper/gradle-wrapper.properties, plugin/build.gradle.kts
build: gradle wrapper 7.3.3
Remove the pinning of groovy 3.0.8, because in gradle 7.3.3, groovy 3.0.9 is used: https://docs.gradle.org/current/userguide/upgrading_version_7.html#changes_7.3
When there's mismatching versions of groovy, these kinds of errors crop up in the spock tests:
```
RewriteDiscoverTest > initializationError FAILED
org.spockframework.util.InternalSpockError at PlatformSpecRunner.java:80
Caused by: java.lang.ExceptionInInitializerError at InvokerHelper.java:88
Caused by: groovy.lang.GroovyRuntimeException at MetaClassRegistryImpl.java:510
RewriteDryRunTest > initializationError FAILED
org.spockframework.util.InternalSpockError at PlatformSpecRunner.java:80
Caused by: java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2
RewriteMetricsPluginTests > …
```
=> build: gradle wrapper 7.3.3

plugin/src/main/java/org/openrewrite/gradle/DefaultRewriteExtension.java, plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java, plugin/src/main/java/org/openrewrite/gradle/isolated/ResourceParser.java
Add the ability to configure which files will be parsed as plain text. If no configuration is applied the defaults for the plugin are:
**/META-INF/services/**
**/.gitignore
**/.gitattributes
**/.java-version
**/.sdkmanrc
**/*.sh
**/*.bash
**/*.bat
**/*.ksh
**/*.txt
**/*.jsp
This is related to https://github.com/openrewrite/rewrite/issues/2134
=> Plain text masks

plugin/src/main/java/org/openrewrite/gradle/ResolveRewriteDependenciesTask.java
Add Java 17 to the list of resolved dependencies so that the plugin can find the
Java 17 parser.
=> Add Java 17 to list of resolved task dependencies

plugin/build.gradle.kts, plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteDryRunTest.kt, plugin/src/test/kotlin/org/openrewrite/gradle/RewritePluginTest.kt, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Changes:
- Kotlin source will be detected and parsed from projects that use the `org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension` plugin.
- Before the changes Kotlin source would only be parsed when the `org.jetbrains.kotlin.jvm` plugin exists in the project.
fixes #181
=> Added support to parse kotlin sources from projects with multiproject plugin.

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
I noticed and corrected a grammatical error in the `rewriteDryRun` task output.
=> Correct grammar mistake in dry run reporting output.

plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
I am adding the groovy plugin to the specific Gradle configuration that is created in the test that is failing. It is the main difference between the failed test and the others that succeed. 
Otherwise, the main branch is broken: https://github.com/openrewrite/rewrite-gradle-plugin/actions/runs/5441989672/jobs/9998886947
This seems related to the python project and the latest changes to introduce the new guava dependency
https://github.com/openrewrite/rewrite-python/commits/main. 
```
Could not resolve com.google.guava:guava:32.1.1-jre.
Required by:
project : > org.openrewrite:rewrite-python:1.1.0-SNAPSHOT:20230706.182507-37
```
I do not know if this is a required/expected change or not. 
@knutwannheden 
@timtebeek 
Revert the change in python, but the previous one was a version that …
=> Fixes the broken build for RewriteRunTest#deleteEmptyDirectory

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java, plugin/src/main/java/org/openrewrite/gradle/isolated/ResourceParser.java, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
The order in what the files have been parsed. Before this change, the resources were parsing kotlin files and producing quarks. Also for kotlin projects, resource files were ignored.
It also checks if settings can not be resolved, which helps to properly write a test that validates the parsing. 
Produce correct LSTs
The order in what the files are produced. 
I am working on a test to be added.
=> Fixes the order to process files to avoid quarks

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Added missing project provenance on Gradle Files
@jkschneider @timtebeek @rpau
=> fixed project provenance on gradle files

plugin/src/main/java/org/openrewrite/gradle/DefaultRewriteExtension.java, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteResolveDependenciesTest.kt
This commit fixes issue #233, where specifying a
rewriteVersion inside the rewrite configuration block would result in rewrite-polyglot failing to resolve to a proper version.
The rewrite-polyglot version can be configured independently from the rewrite version.
See #233.
=> fix: use separate rewrite-polyglot version (#233)

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Fixes https://github.com/moderneinc/customer-requests/issues/48
Exclude parsing generated Kotlin sources from `protos/build/generated`
=> exclude parse kotlin files under path `protos/build/generated`

README.md, settings.gradle.kts
- Added Revved up by Develocity badge
- Bumped Gradle Enterprise and Common Custom User Data plugins to latest versions
- Updated remote build cache config to only push when authenticated
- Bumped Gradle Enterprise and Common Custom User Data plugins to latest versions -> improved scans and support for gradle enterprise (server) 2023.4
- Updated remote build cache config to only push when authenticated -> if an unauthenticated push is attempted remote build cache will get turned off for the rest of the build. This can happen (does) on forked PR builds which run in an unsecure environment. 
In general, we strongly suggest to apply these fixes/updates to the rest of your projects, especially if you have a nice rewrite rule to do it for you 😄
=> Update gradle enterprise setup

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java, plugin/src/main/kotlin/org/openrewrite/gradle/GradleProjectSpec.kt, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Fixed the bug with resources in subproject being excluded from processing.
I have a multi-module project like this:
```
.
├── src
│   └── main
│       └── resources
│           └── application-root.yml
└── subproject
└── src
└── main
└── resources
└── application-subproject.yml  
```
And I have a custom recipe to modify some YAML. While the `application-root.yml` is correctly modified, the `application-subproject.yml` is skipped. It is reproduced in the `resources in subproject committed to git are correctly processed` test case.
There is already a test case `rewriteRun applies recipe to a multi-project build` which aims to verify this situation, but it doesn't check the case when Git repo is available. There is a different code path in `OmniParser` for such case and it's not reached.
I …
=> Fix resources exclusion in a multi-module project with git repo

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
This commit reverts 8868dcff30f63511725961220e977d3d985d134c again. The compile classpath entries can contain important dependencies like Lombok, which typically don't exist on the runtime classpath.
=> Include compile classpath in dependencies

suppressions.xml
related: https://github.com/moderneinc/dependency-vulnerability-reports/issues/648
=> chore: suppression was limited to specific file path when we want just cve match

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java, plugin/src/main/kotlin/org/openrewrite/gradle/GradleProjectSpec.kt, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Fixes #285 
rewriteRun now respects the file encoding of the Gradle Java Plugin
=> Fix for Java source file encoding different from UTF-8

plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java, plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.7/userguide/upgrading_version_8.html#java_convention_deprecation
Fixes #307
=> Stop using JavaPluginConvention for Gradle 7.1+

plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java, plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Added the ability to export data tables.
I was reading about them in the docs and found that they were only implemented in maven and there was a request to add them to the gradle plugin. 
I did see that this open issue that talks about adding some configuration that would allow you more control over turning certain csv exports on or off. From a cursory look, it seems like I might have to change rewrite-core for that to work. I'm not opposed to doing that, but I thought I'd create this PR to get thoughts before moving too far forward.
I did not add any tests yet either. I'll be more than happy to update this to a prod-ready state.
I added to the `RewriteExtension`:
```
rewrite {
exportDatatables = true
}
```
It defaults to false.
Here's a screenshot of the cvs file output:
=> Add ability to export dataTables

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Add JavaVersion marker to files in Java project resources directories
For parity with the [Maven plugin](https://github.com/openrewrite/rewrite-maven-plugin/blob/f1711dc2d1dff52d089248b7f6376bd361d96896/src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java#L421-L435) which adds the JavaVersion marker also to files in Java resources directories.
Without this fix, for example, the [EnableVirtualThreads](https://github.com/openrewrite/rewrite-spring/blob/1572696591829a8be8d9d85ed440354bc8bd1892/src/main/resources/META-INF/rewrite/spring-boot-32.yml#L69-L79) recipe does no changes if executed via the Gradle plugin, while the Maven plugin performs the expected changes:
**Maven Plugin:**
```console
[INFO] --- rewrite:5.36.0:run (default-cli) @ java-version-marker ---
[INFO] Using …
```
=> Add JavaVersion marker to files in Java project resources directories

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Previously we looked at `source instanceof ParseError`, but there might be cases in the future where a file parsed correctly, but got assigned a marker for a different reason. Up to now that had been exclusive to Maven files, but figured it good to support here as well.
Over on the Maven side we saw files silently having error markers, with no indication that they failed to resolve. This ensures if that happens for files that show in the Gradle side of things then we are ready to show those here as well.
- Mimics https://github.com/openrewrite/rewrite-maven-plugin/pull/833
=> Look for ParseExceptionResult marker instead of instanceof ParserError

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Reuse the mechanism we added for `protos/build/generated` for `build/generated-sources`.
Files like `build-src/build/generated-sources` are parsed into the LST, and modified by recipes. That last part is undesirable, as the diffs would then target files not part of the git repository, and fail to apply from a dryRun fix.patch file.
n | sourcePath | sourceFileType | buildTool | buildToolVersion | checksum | lineCount
-- | -- | -- | -- | -- | -- | --
1 | build-src/build/generated-sources/kotlin-dsl-external-plugin-spec-builders/kotlin/gradle/kotlin/dsl/plugins/_12895b5fa930feaf40eec89923f04a18/PluginSpecBuilders.kt | K.CompilationUnit | modgradle | 3.17.0 | 55d3a6f819a2d911e8dc50fcdba328c6 | 1186
2 | build-src/build/generated-sources/kotlin-dsl-accessors/kotlin/gradle/kotlin/dsl/accessors/_f …
=> Do not add Kotlin and Groovy sources from `build/` to LST

plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
The RewritePlugin was changed to call the register() method instead of the create() method for the three tasks. This method takes a configuration lambda where the existing configuration can be done. Next, the tasks' usages were replaced with the equivalent TaskProvider reference. Finally, fetching the appropriate JavaCompile tasks was updated to use a lazy load method (named()), so those tasks are not eagerly created. The plugin's Gradle version was unchanged and should still support Gradle 4.10.
- fixes #288 
The current structure of RewritePlugin eagerly loads the RewriteRun, RewriteDryRun, and RewriteDiscover tasks. This is a problem in Gradle builds with a large number of modules, as it has to create hundreds or even thousands of tasks during configuration. This will happen even if …
=> Update RewritePlugin to load tasks lazily

plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Change output directory for datatables from `<repository top directory>/build/rewrite/datatables` to `<gradle project directory>/build/reports/rewrite/datatables`
Currently, when `setExportDatatables()` is set to `true`, the CSV files are exported to `<repository top directory>/build/datatables`. However, I believe it would be better to change the output to the `build` directory of each Gradle projects for the following two reasons.
1. If the Gradle project's directory is different from the repository's top directory, the CSV files will not be deleted when the `clean` task is executed.
2. In a multi-project structure built with Gradle, it is easier to understand the relevance if the CSV files are output to the `build` directory of each project.
Files related to reports output during the …
=> Change output directory path for Datatables

plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Removed dependency copying out of the `rewrite` configuration to a hidden detached one.
We have internal tooling that relies on being able to attach to configurations with a `beforeResolve` hook override dependencies and provide centralized dependency versioning. With the detached configuration there is not way to attach the hook and dependency resolution fails. By removing the detached configuration in favor of the `rewrite` configuration we should be able to use normal hooks as expected.
We've attempted several approaches without modifying the existing plugin but each has run into subtle problems.
* Resolving our internal dependencies first (currently a library of internal recipes) and injecting the resovled files as dependencies. - Lead to duplicated jars on the classpath.
* Replacing …
=> Simplify Plugins approach to adding dependencies so that it no longer uses a hidden detached configuration.

plugin/src/main/java/org/openrewrite/gradle/isolated/AndroidProjectParser.java, plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
To avoid swallowing throwables from parsers.
=> Reuse ExecutionContext with onError for Omniparser

build.gradle.kts, metrics/build.gradle.kts
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/820
=> chore: update org.owasp.dependencycheck to latest.release

plugin/src/test/kotlin/org/openrewrite/gradle/GradleRunnerTest.kt, plugin/src/test/kotlin/org/openrewrite/gradle/RewriteDryRunSourceSetTest.kt, plugin/src/test/kotlin/org/openrewrite/gradle/RewritePluginTest.kt, plugin/src/test/kotlin/org/openrewrite/gradle/fixtures/GradleFixtures.kt, plugin/src/test/kotlin/org/openrewrite/gradle/fixtures/JavaFixtures.kt
Just added test cases.
Verify that the handling of Java source files in custom source sets works as expected.
I am working on a project that seems to have issue with resolving types in the LST when running a recipe. I suspected that it has something to do with definition of custom Gradle source sets, however, all my tests pass.
=> Add test cases for verifying custom source set handling
