- plugin/src/test/groovy/org/openrewrite/gradle/RewritePluginTest.groovy
separate out multi-build test
- add test for multi-build projects using autoformat
- update test using third-party dependencies to point to maven central and use updated test name
formatting by moving expected results around
> separate test for multi-build projects into one using autoformat, one using junit 4 to 5

- buildSrc/src/main/groovy/org/gradle/rewrite/build/GradleVersionData.groovy
- plugin/build.gradle.kts
- plugin/src/main/java/org/openrewrite/gradle/MeterRegistryProvider.java
- plugin/src/main/java/org/openrewrite/gradle/RewriteDiscoverTask.java
- plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java
- plugin/src/main/java/org/openrewrite/gradle/RewriteFixTask.java
- plugin/src/main/java/org/openrewrite/gradle/RewriteMetricsPlugin.java
- plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
- plugin/src/main/java/org/openrewrite/gradle/RewriteWarnTask.java
- plugin/src/test/groovy/org/openrewrite/gradle/RewriteTestBase.groovy
it's just formatting, should not be anything _semantic_
> autoformat source code before making any other structural changes to establish git diff baseline

- plugin/src/test/groovy/org/openrewrite/gradle/RewriteDiscoverTest.groovy
- plugin/src/test/groovy/org/openrewrite/gradle/RewriteDryRunTest.groovy
- plugin/src/test/groovy/org/openrewrite/gradle/RewriteRunTest.groovy
- plugin/src/test/groovy/org/openrewrite/gradle/RewriteTestBase.groovy
quick improvement for troubleshooting
(https://github.com/openrewrite/rewrite-gradle-plugin/issues/29)
> separate tests by function to improve readability and runtime efficiency during debugging

- plugin/src/main/java/org/openrewrite/gradle/RewriteDiscoverTask.java
- plugin/src/test/groovy/org/openrewrite/gradle/RewriteDiscoverTest.groovy
`rewriteDiscover` output to match the changes made in https://github.com/openrewrite/rewrite-maven-plugin/pull/150 which has the "available recipes" first, then "available styles", then "active styles", then "active recipes". Summary at the bottom.
```
Available Recipes:
name: org.openrewrite.java.AddApache2LicenseHeader
name: org.openrewrite.java.cleanup.Cleanup
name: org.openrewrite.java.search.FindSecrets
name: org.openrewrite.java.security.JavaSecurityBestPractices
name: org.openrewrite.java.security.ResultOfFileMkdirsIgnored
name: org.openrewrite.java.AddLicenseHeader
name: org.openrewrite.java.ChangeMethodName
name: org.openrewrite.java.ChangeMethodTargetToStatic
name: org.openrewrite.java.ChangeMethodTargetToVariable
name: org.openrewrite.java.ChangePackage
name: …
```
> RewriteDiscover output with available and active styles, results summary at the bottom.

- plugin/src/main/java/org/openrewrite/gradle/AbstractRewriteTask.java
Updating `gradle-plugin` to match `maven-plugin` execution status logging as per https://github.com/openrewrite/rewrite-maven-plugin/pull/156 and https://github.com/openrewrite/rewrite-maven-plugin/pull/160
> Polish execution status logging

- plugin/src/main/java/org/openrewrite/gradle/RewriteDiscoverTask.java
- plugin/src/main/java/org/openrewrite/gradle/RewriteReflectiveFacade.java
- plugin/src/main/java/org/openrewrite/gradle/ui/RecipeDescriptorTree.java
- plugin/src/main/java/org/openrewrite/gradle/ui/RecipeDescriptorTreePrompter.java
- plugin/src/main/java/org/openrewrite/gradle/ui/package-info.java
prompt user for filtering information when searching available recipes to display, see: https://github.com/openrewrite/rewrite-maven-plugin/pull/155
```sh
./gradlew rewriteDiscoverMain --interactive
```
🤔
> RewriteDiscover categorized recipes available on classpath

- plugin/src/main/java/org/openrewrite/gradle/RewriteDiscoverTask.java
Gradle implementation of https://github.com/openrewrite/rewrite-maven-plugin/pull/164
> Change discover display based on feedback and current reference documentation layout

- plugin/src/main/java/org/openrewrite/gradle/MeterRegistryProvider.java
- plugin/src/main/java/org/openrewrite/gradle/RewriteDryRunTask.java
Co-authored-by: Moderne <team@moderne.io>
> refactor: Parameterize SLF4J logging statements

- .github/workflows/integration-tests.yml
- scripts/test.init.gradle
This is still a work in progress-- merging to main to keep things pulled in, but this is not the best pattern to use. Like, at all. We'll get it worked out, no worries though.
> Applying gradle-init script to external repositories using github actions

- .github/workflows/ci.yml
- README.md
- build.gradle.kts
https://github.com/openrewrite/rewrite-gradle-plugin/issues/84
Tested over in https://github.com/slugstack/slugstack-gradle-plugin
> [#84] Publish rewrite-gradle-plugin snapshots to OSSRH

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Changes:
- Gradle plugin will write changes to the file in the detected encoding.
> Updated plugin to use source file encoding.

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
- plugin/src/main/java/org/openrewrite/gradle/isolated/ResourceParser.java
Changes:
- ResourceParser will collect all applicable resources in one file traversal.
fixes #109
> Updated resource parser to collect resources in file traversal

- plugin/src/main/java/org/openrewrite/gradle/isolated/ResourceParser.java
Changes:
- Added support for quarks.
fixes #108
> Added QuarkParser to ResourceParser

- plugin/src/main/java/org/openrewrite/gradle/isolated/ResourceParser.java
This PR matches a parallel one in rewrite-maven-plugin https://github.com/openrewrite/rewrite-maven-plugin/pull/344
and solves https://github.com/openrewrite/rewrite-gradle-plugin/issues/116
> parse spi config files as Plain Text

- gradle/wrapper/gradle-wrapper.properties
See https://github.com/openrewrite/rewrite/issues/2648
> build: configure gradle checksum verification

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
> Filter out build from source files

- metrics/src/main/java/org/openrewrite/gradle/GradleLoggingMeterRegistry.java
- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
- plugin/src/main/java/org/openrewrite/gradle/isolated/ResourceParser.java
Spurred on by https://github.com/openrewrite/rewrite/issues/3032 I thought to apply the best practice recipes where they made notable changes. Running these now also ensures we're in a better state when we add pull request checks on no-outstanding-changes.
> refactor: SLF4J best practices

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Relates to https://github.com/openrewrite/rewrite/pull/3105 and https://github.com/openrewrite/rewrite-kotlin/pull/95.
Fixes https://github.com/openrewrite/rewrite/issues/3053.
> Correctly and completely manage source set assignment to all compilation units

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
The JVM-based parsers should not all share the same `JavaTypeCache`, especially not in multi-module builds or across source set boundaries.
> Remove global shared `JavaTypeCache`

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
> Lazily load parsers for better per-source set memory consumption

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Add Kotlin autoDetect to the Gradle plug-in.
> Add kotlin autoDetect

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Added a log message of active styles on the parser
> added log message for active styles

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
- plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Parse gradle wrapper files separately from other resource files, such that they get the markers expected in [UpdateGradleWrapper](https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java).
Fixes moderneinc/moderne-gradle-plugin#142
Didn't see a good option to test that the files are indeed parsed as non-resource files, other than using breakpoints in the debugger. It works, but it can be broken. Any suggestions for a better test assertion?
Also figured we'd only pick up Gradle wrapper files from the root project; would you agree there?
As discussed on the issue linked above
> Parse Gradle wrapper files separately

- build.gradle.kts
- suppressions.xml
- Update org.owasp.dependencycheck to be on the latest. 
- Adds NVD key setting (pulled from the environment at build time) 
- Adds suppressions.xml file. 
Fix dependency check aggregate task
> fix: add missing file and nvd api key

- suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/615
> chore: update suppressions 01222024121504

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Consistently add the GradleProject marker to `gradle.properties` files, even when other resources are skipped.
The GradleProject marker is now used in `UpgradeDependencyVersion`, and as such needs to be present to bump version there.
Also removed the class wide `@SuppressWarnings("unused")`, as lead to some puzzling code choices. Small change that whe we have to cascade down.
- https://github.com/openrewrite/rewrite/pull/3901
> Add GradleProject marker to `gradle.properties`

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Follow up from this earlier PR that copied the approach for Gradle Wrappers, but those only needed the BuildTool marker for the Gradle version, not the full GradleProject marker to access repositories to resolve dependencies and plugins.
- https://github.com/openrewrite/rewrite-gradle-plugin/pull/267
> Add GradleProject marker to `gradle.properties` to access repositories

- suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/622
> chore: update suppressions for 01-31-2024 vulnerability report

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
This allows run parsing to run multiple times
> Add check to make sure rewriteImplementation has not already been exended

- plugin/src/main/java/org/openrewrite/gradle/RewriteDryRunTask.java
- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
use `Project.getLayout().getBuildDirectory()` instead
> Stop using deprecated Project.getBuildDir()

- suppressions.xml
Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/643
> chore: 03-27-2024 vulnerability report suppressions

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
- plugin/src/test/kotlin/org/openrewrite/gradle/RewriteDryRunTest.kt
- plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
- Following https://github.com/openrewrite/rewrite/pull/4349
> Recipe descriptions should end in a dot

- suppressions.xml
related to:
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/703
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/704
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/706
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/707
> chore(suppressions): Add suppression for develocity-gradle-plugin CVE

- plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
- suppressions.xml
- relating to https://github.com/moderneinc/dependency-vulnerability-reports/issues/727
> chore: update develocity-gradle-plugin vulnerability suppressions

- plugin/build.gradle.kts
- https://github.com/openrewrite/rewrite-maven-plugin/pull/872
- https://github.com/openrewrite/rewrite/issues/4534
- https://github.com/openrewrite/rewrite/pull/4516
> Add rewrite-java-21

- suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/753
> chore: update suppression 10222024194941

- plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.AnnotateNullableMethods?organizationId=T3BlblJld3JpdGU%3D
> refactor: Annotate methods which may return `null` with `@Nullable`

- suppressions.xml
related to:
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/776
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.xml.security.UpdateOwaspSuppressionDate?organizationId=T3BlblJld3JpdGU%3D#defaults=W3sidmFsdWUiOlsiQ1ZFLTIwMTctMTI2MjYiLCJDVkUtMjAxOS0xNTA1MiIsIkNWRS0yMDIzLTM1OTQ3ICIsIkNWRS0yMDIxLTI5NDI4IiwiQ1ZFLTIwMjAtMTE5NzkiLCJDVkUtMjAyMS0zMjc1MSIsIkNWRS0yMDIzLTQ1MTYxIiwiQ1ZFLTIwMjMtNDUxNjMiLCJDVkUtMjAyMy01OTY0ICIsIkNWRS0yMDE5LTExNDAyIiwiQ1ZFLTIwMTktMTE0MDMiLCJDVkUtMjAyMS00MTU4OSIsIkNWRS0yMDIzLTQ5MjM4IiwiQ1ZFLTIwMjItMjUzNjQiLCJDVkUtMjAyMi0xNDcxIiwiQ1ZFLTIwMTgtMTI1OCJdLCJuYW1lIjoiY3ZlTGlzdCJ9XQ==
> refactor: update OWASP suppression date bounds

- plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
- plugin/src/test/kotlin/org/openrewrite/gradle/RewritePluginTest.kt
- plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Revert https://github.com/openrewrite/rewrite-gradle-plugin/commit/147c7effda5b9ef521ca6d8a341fde69d9881c56 from 
- https://github.com/openrewrite/rewrite-gradle-plugin/pull/345
- Fix #348
- Fix #349
- Fix #351
- Fix #352
> Revert to hidden detached configuration

- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Switch parsing of Gradle Kotlin DSL files over to the `GradleParser`.
https://github.com/openrewrite/rewrite/pull/5122
Nothing in particular
Anybody
N/A
N/A
> Gradle Kotlin DSL Support

- plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
- Pending https://github.com/gradle/gradle/issues/33152
- Fixes https://github.com/openrewrite/rewrite-gradle-plugin/issues/378
> Avoid `stream()` on `org.gradle.api.artifacts.Configuration.getDependencies`

- plugin/src/main/java/org/openrewrite/gradle/isolated/AndroidProjectParser.java
- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
More tightly/closely control setting of the charset to only effect the current parser's work and ensure that the charset is cleared when that work has completed.
Prior to this change, only the last invocation to `ParsingExecutionContextView.view(ctx).setCharset(..)` would have been observed by parsers attempting to parse source input. This is as a result of the stream being constructed during the discovery of source files, but only executed when a terminal operator is called -- in this case the `collect(toList())` invocation.
While working through this, I also observed some inadvertent deviation from expected default charsets for Kotlin and Android so those have been corrected as part of this PR.
N/A
@sambsnyd 
N/A
N/A
> Prevent leaking of charset between source sets and after the last source set

- plugin/src/main/java/org/openrewrite/gradle/isolated/AndroidProjectParser.java
- plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
> OpenRewrite recipe best practices
